stages:
  - build
  - test

build:
  stage: build
  image: python:3.10
  script:
    - python -m build


test:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - python -m unittest test_module.py

