stages:
  - test
  - build


test:
  stage: test
  image: python:3.10
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m unittest .\tests\test_module.py

build:
  stage: build
  image: python:3.10
  script:
    - python -m build
  artifacts:
    paths:
      - /dist/*





