stages:
  - test
  - build


test:
  stage: test
  image: python:3.10
  script:
    - python -m venv myenv
    - source myenv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m unittest

build:
  stage: build
  image: python:3.10
  script:
    - python3 -m venv myenv
    - . myenv/bin/activate
    - pip install --upgrade pip
    - pip install hatchling


    - hatchling build

  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz





